{
    # Disables the client, and starts only the server
    # The server will be made available on the specified port
    "publicserver": false,

    # Serve pprof on localhost:6060. Used for debugging.
    "servepprof": false,

    # The radius of chunks around the player that will be rendered, measured in chunks.
    "renderdistance": 10,

    "client": {
        # The width & height the game window starts at
        "defaultwidth": 1920,
        "defaultheight": 1080,
    },

    "server": {
        # The address a public server will bind to.
        # If left empty, the server will bind to all interfaces.
        "address": "",

        # The port a public server will bind to
        "port": 53785,
    }
}
